# Generated by Django 3.0.5 on 2020-04-28 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dnsbl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelistedip',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
